# Generated by Django 3.2 on 2023-09-03 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('spenxy_card_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('limit', models.FloatField()),
                ('available', models.FloatField()),
                ('used', models.FloatField()),
                ('opening_balance', models.FloatField()),
                ('topup_balance', models.FloatField()),
                ('limit_per_transaction', models.FloatField()),
                ('pending_balance', models.FloatField()),
                ('fees_balance', models.FloatField()),
                ('incoming_balance', models.FloatField()),
                ('withdrawal_balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.CharField(max_length=255)),
                ('closed_at', models.CharField(blank=True, max_length=255, null=True)),
                ('mask_number', models.CharField(max_length=16)),
                ('nick_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('is_autolimit', models.BooleanField()),
                ('is_withdrawable', models.BooleanField()),
                ('available', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CardTransactions',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('bin', models.CharField(max_length=255)),
                ('mask_number', models.CharField(max_length=16)),
                ('card_memo', models.CharField(max_length=255)),
                ('card_status', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('billing_amount', models.FloatField()),
                ('billing_currency', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=255)),
                ('charge', models.FloatField()),
                ('status', models.CharField(max_length=255)),
                ('merchant_name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cards.card')),
            ],
        ),
        migrations.CreateModel(
            name='CardDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=255)),
                ('cvv', models.CharField(max_length=3)),
                ('expiry_month', models.IntegerField()),
                ('expiry_year', models.IntegerField()),
                ('name_on_card', models.CharField(max_length=255)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='cards.card')),
            ],
        ),
    ]
